### ISSUE TITLE
NameError: name 'gramian_angular_field' is not defined

### ISSUE THREAD

**Issue by zapaishchykova** [devitrylouis/imaging_time_series#3]
Hi, 
trying to launch and getting the following error:
```
Traceback (most recent call last):
  File "C:/Users/zapai/Downloads/imaging_time_series-master/imaging_time_series-master/make_frame.py", line 92, in <module>
    animation = VideoClip(make_frame, duration=2)
  File "D:\Installed\Anaconda\lib\site-packages\moviepy\video\VideoClip.py", line 86, in __init__
    self.size = self.get_frame(0).shape[:2][::-1]
  File "<decorator-gen-10>", line 2, in get_frame
  File "D:\Installed\Anaconda\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "D:\Installed\Anaconda\lib\site-packages\moviepy\Clip.py", line 95, in get_frame
    return self.make_frame(t)
  File "C:/Users/zapai/Downloads/imaging_time_series-master/imaging_time_series-master/make_frame.py", line 43, in make_frame
    gaf, phi, r, scaled_time_serie = gramian_angular_field(time_serie)
NameError: name 'gramian_angular_field' is not defined

Process finished with exit code 1


```

**Comment by zapaishchykova** [comment]
okay, i fixed this please check my fork in case you also struggle
